# Generated by Django 3.1.7 on 2021-03-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_transactionuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionuser',
            name='account_no',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
